In [2]:
import numpy as np

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [42]:
arr = np.random.normal(size =(10, 10))
print(np.max(arr))
print(np.min(arr))

3.5614049599485407
-2.6022661088220005


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [3]:
arr = np.ones((3,3))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
