In [1]:
import numpy as np

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [5]:
# help(np.arange)
# help(np.dtype)
jul_2016 = np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
print(jul_2016)

# here I was also testing the functionality of the 'dtype' attribute, but its not part of the exercise
# year = np.arange('2022', '2023', dtype = 'datetime64[M]')
# print(year)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [293]:
a = np.random.randint(2, 4, 6)
print(a)
b = np.random.randint(2, 4, 6)
print(b)
np.allclose(a, b)

[3 3 3 3 3 3]
[2 3 2 2 2 2]


False

#### 43. Make an array immutable (read-only) (★★☆)

In [79]:
arr = np.ones((3,3))
print(arr)
arr.flags.writeable = False
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


ValueError: assignment destination is read-only