In [1]:
import numpy as np

#### 72. How to swap two rows of an array? (★★★)

In [50]:
def change_rows(arr, row1, row2):
    arr[[row1-1]], arr[[row2-1]] = arr[[row2-1]], arr[[row1-1]]
    print(arr)

array = np.array([[1,2,3], [3,2,1], [2,4,6], [6,4,2]])
change_rows(array, 1, 4)

[[6 4 2]
 [3 2 1]
 [2 4 6]
 [1 2 3]]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [65]:
def sliding_average(array, n):
    averages = []
    for i in range(len(array)-(n-1)):
        a = sum(array[0 + i.__index__():n + i.__index__()]) / n
        averages.append(a)
    return averages
arr = np.arange(1, 11)
sliding_average(arr, 4)

[2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5]

In [64]:
#Another solution, using slicing only to define the windows
def average(array, n):
    s = np.cumsum(array)
    s[n:] = s[n:] - s[:-n]
    return s[n-1:] / n

arr = np.arange(1, 11)
average(arr, 4)


array([2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5])